version: "3.2"
services:
  php:
    restart: always
    build:
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  python:
    restart: always
    build:
      context: './python/'
      args:
       PYTHON_VERSION: ${PYTHON_VERSION}
    networks:
      - backend
    ports:
      - "10000:8888"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: python
  apache:
    restart: always
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - postgis
      - python
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
  postgis:
    image: kartoza/postgis:${POSTGIS_VERSION}
    restart: always
    ports:
      - "25432:5432"
    volumes:
      - data:/var/lib/psql
    networks:
      - backend
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASS=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgis
networks:
  frontend:
  backend:
volumes:
    data:
        external: true
